// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: block.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCommand = `-- name: GetCommand :one
SELECT id, vin, fleet, action, state, correlation_id, created_at, sent_at, updated_at
FROM commands
WHERE id = $1
`

func (q *Queries) GetCommand(ctx context.Context, id string) (Command, error) {
	row := q.db.QueryRow(ctx, getCommand, id)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.Vin,
		&i.Fleet,
		&i.Action,
		&i.State,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.SentAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasLeasingVehicle = `-- name: HasLeasingVehicle :one
SELECT EXISTS (
    SELECT 1
    FROM vehicles
    WHERE vin = $1 AND fleet = 'leasing'
)
`

func (q *Queries) HasLeasingVehicle(ctx context.Context, vin string) (bool, error) {
	row := q.db.QueryRow(ctx, hasLeasingVehicle, vin)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (action, payload)
VALUES ($1, $2)
`

type InsertAuditLogParams struct {
	Action  string
	Payload []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog, arg.Action, arg.Payload)
	return err
}

const insertCommand = `-- name: InsertCommand :exec
INSERT INTO commands (id, vin, fleet, action, state, correlation_id, sent_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertCommandParams struct {
	ID            string
	Vin           string
	Fleet         string
	Action        string
	State         string
	CorrelationID string
	SentAt        pgtype.Timestamptz
}

func (q *Queries) InsertCommand(ctx context.Context, arg InsertCommandParams) error {
	_, err := q.db.Exec(ctx, insertCommand,
		arg.ID,
		arg.Vin,
		arg.Fleet,
		arg.Action,
		arg.State,
		arg.CorrelationID,
		arg.SentAt,
	)
	return err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (topic, payload)
VALUES ($1, $2)
`

type InsertOutboxParams struct {
	Topic   string
	Payload []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.Topic, arg.Payload)
	return err
}

const listActiveLeasingCommands = `-- name: ListActiveLeasingCommands :many
SELECT id, vin, fleet, action, state, correlation_id, created_at, sent_at, updated_at
FROM commands
WHERE fleet = 'leasing'
  AND state IN ('REQUESTED', 'ARMED', 'SENT')
ORDER BY created_at
`

func (q *Queries) ListActiveLeasingCommands(ctx context.Context) ([]Command, error) {
	rows, err := q.db.Query(ctx, listActiveLeasingCommands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Command{}
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.Vin,
			&i.Fleet,
			&i.Action,
			&i.State,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.SentAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestAckedLeasing = `-- name: ListLatestAckedLeasing :many
SELECT DISTINCT ON (vin)
    id, vin, fleet, action, state, correlation_id, created_at, sent_at, updated_at
FROM commands
WHERE fleet = 'leasing' AND state = 'ACKED'
ORDER BY vin, updated_at DESC
`

func (q *Queries) ListLatestAckedLeasing(ctx context.Context) ([]Command, error) {
	rows, err := q.db.Query(ctx, listLatestAckedLeasing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Command{}
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.Vin,
			&i.Fleet,
			&i.Action,
			&i.State,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.SentAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsentOutbox = `-- name: ListUnsentOutbox :many
SELECT id, topic, payload, created_at
FROM outbox
WHERE sent_at IS NULL
ORDER BY id
LIMIT $1
`

type ListUnsentOutboxRow struct {
	ID        int64
	Topic     string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListUnsentOutbox(ctx context.Context, limit int32) ([]ListUnsentOutboxRow, error) {
	rows, err := q.db.Query(ctx, listUnsentOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnsentOutboxRow{}
	for rows.Next() {
		var i ListUnsentOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE outbox
SET sent_at = $2
WHERE id = $1
`

type MarkOutboxSentParams struct {
	ID     int64
	SentAt pgtype.Timestamptz
}

func (q *Queries) MarkOutboxSent(ctx context.Context, arg MarkOutboxSentParams) error {
	_, err := q.db.Exec(ctx, markOutboxSent, arg.ID, arg.SentAt)
	return err
}

const updateCommandState = `-- name: UpdateCommandState :exec
UPDATE commands
SET state = $2,
    sent_at = COALESCE($3::timestamptz, sent_at),
    updated_at = now()
WHERE id = $1
`

type UpdateCommandStateParams struct {
	ID     string
	State  string
	SentAt pgtype.Timestamptz
}

func (q *Queries) UpdateCommandState(ctx context.Context, arg UpdateCommandStateParams) error {
	_, err := q.db.Exec(ctx, updateCommandState, arg.ID, arg.State, arg.SentAt)
	return err
}
