// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: book.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveContracts = `-- name: CountActiveContracts :one
SELECT count(*)::bigint
FROM contracts
WHERE ended_on IS NULL
`

func (q *Queries) CountActiveContracts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveContracts)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const endContract = `-- name: EndContract :exec
UPDATE contracts
SET ended_on = $2
WHERE id = $1
`

type EndContractParams struct {
	ID      pgtype.UUID
	EndedOn pgtype.Date
}

func (q *Queries) EndContract(ctx context.Context, arg EndContractParams) error {
	_, err := q.db.Exec(ctx, endContract, arg.ID, arg.EndedOn)
	return err
}

const incrementPaidCount = `-- name: IncrementPaidCount :exec
UPDATE contracts
SET paid_count = paid_count + 1
WHERE id = $1
`

func (q *Queries) IncrementPaidCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementPaidCount, id)
	return err
}

const insertContract = `-- name: InsertContract :one
INSERT INTO contracts (
    customer_id,
    vin,
    installment_value,
    total_installments,
    paid_count,
    payer_profile,
    started_on
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id
`

type InsertContractParams struct {
	CustomerID        pgtype.UUID
	Vin               string
	InstallmentValue  pgtype.Numeric
	TotalInstallments int32
	PaidCount         int32
	PayerProfile      string
	StartedOn         pgtype.Date
}

func (q *Queries) InsertContract(ctx context.Context, arg InsertContractParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertContract,
		arg.CustomerID,
		arg.Vin,
		arg.InstallmentValue,
		arg.TotalInstallments,
		arg.PaidCount,
		arg.PayerProfile,
		arg.StartedOn,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertCustomer = `-- name: InsertCustomer :one
INSERT INTO customers (name)
VALUES ($1)
RETURNING id
`

func (q *Queries) InsertCustomer(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCustomer, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertInstallment = `-- name: InsertInstallment :one
INSERT INTO installments (contract_id, due_on, amount)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertInstallmentParams struct {
	ContractID pgtype.UUID
	DueOn      pgtype.Date
	Amount     pgtype.Numeric
}

func (q *Queries) InsertInstallment(ctx context.Context, arg InsertInstallmentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertInstallment, arg.ContractID, arg.DueOn, arg.Amount)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPayment = `-- name: InsertPayment :exec
INSERT INTO payments (contract_id, installment_id, amount, source, paid_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPaymentParams struct {
	ContractID    pgtype.UUID
	InstallmentID pgtype.UUID
	Amount        pgtype.Numeric
	Source        string
	PaidAt        pgtype.Timestamptz
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) error {
	_, err := q.db.Exec(ctx, insertPayment,
		arg.ContractID,
		arg.InstallmentID,
		arg.Amount,
		arg.Source,
		arg.PaidAt,
	)
	return err
}

const listActiveContracts = `-- name: ListActiveContracts :many
SELECT
    c.id,
    c.vin,
    c.payer_profile,
    c.installment_value,
    c.total_installments,
    c.paid_count,
    c.started_on,
    cu.name AS customer_name
FROM contracts c
JOIN customers cu ON cu.id = c.customer_id
JOIN vehicles v ON v.vin = c.vin
WHERE c.ended_on IS NULL
  AND v.fleet = 'leasing'
ORDER BY cu.name, c.vin
`

type ListActiveContractsRow struct {
	ID                pgtype.UUID
	Vin               string
	PayerProfile      string
	InstallmentValue  pgtype.Numeric
	TotalInstallments int32
	PaidCount         int32
	StartedOn         pgtype.Date
	CustomerName      string
}

func (q *Queries) ListActiveContracts(ctx context.Context) ([]ListActiveContractsRow, error) {
	rows, err := q.db.Query(ctx, listActiveContracts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveContractsRow{}
	for rows.Next() {
		var i ListActiveContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.Vin,
			&i.PayerProfile,
			&i.InstallmentValue,
			&i.TotalInstallments,
			&i.PaidCount,
			&i.StartedOn,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveInstallments = `-- name: ListActiveInstallments :many
SELECT i.id, i.contract_id, i.due_on, i.amount
FROM installments i
JOIN contracts c ON c.id = i.contract_id
WHERE c.ended_on IS NULL
ORDER BY i.due_on
`

func (q *Queries) ListActiveInstallments(ctx context.Context) ([]Installment, error) {
	rows, err := q.db.Query(ctx, listActiveInstallments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Installment{}
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.DueOn,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePayments = `-- name: ListActivePayments :many
SELECT p.id, p.contract_id, p.installment_id, p.amount, p.source
FROM payments p
JOIN contracts c ON c.id = p.contract_id
WHERE c.ended_on IS NULL
`

type ListActivePaymentsRow struct {
	ID            pgtype.UUID
	ContractID    pgtype.UUID
	InstallmentID pgtype.UUID
	Amount        pgtype.Numeric
	Source        string
}

func (q *Queries) ListActivePayments(ctx context.Context) ([]ListActivePaymentsRow, error) {
	rows, err := q.db.Query(ctx, listActivePayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePaymentsRow{}
	for rows.Next() {
		var i ListActivePaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.InstallmentID,
			&i.Amount,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFreeLeasingVins = `-- name: ListFreeLeasingVins :many
SELECT v.vin
FROM vehicles v
WHERE v.fleet = 'leasing'
  AND NOT EXISTS (
    SELECT 1
    FROM contracts c
    WHERE c.vin = v.vin
      AND c.ended_on IS NULL
  )
ORDER BY v.vin
`

func (q *Queries) ListFreeLeasingVins(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listFreeLeasingVins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var vin string
		if err := rows.Scan(&vin); err != nil {
			return nil, err
		}
		items = append(items, vin)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
