// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIdempotency = `-- name: GetIdempotency :one
SELECT contract_id, action, key, resource_id, status_code, body
FROM idempotency_keys
WHERE contract_id = $1 AND action = $2 AND key = $3
`

type GetIdempotencyParams struct {
	ContractID pgtype.UUID
	Action     string
	Key        string
}

type GetIdempotencyRow struct {
	ContractID pgtype.UUID
	Action     string
	Key        string
	ResourceID string
	StatusCode int32
	Body       []byte
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (GetIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotency, arg.ContractID, arg.Action, arg.Key)
	var i GetIdempotencyRow
	err := row.Scan(
		&i.ContractID,
		&i.Action,
		&i.Key,
		&i.ResourceID,
		&i.StatusCode,
		&i.Body,
	)
	return i, err
}

const insertIdempotency = `-- name: InsertIdempotency :exec
INSERT INTO idempotency_keys (contract_id, action, key, resource_id, status_code, body)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertIdempotencyParams struct {
	ContractID pgtype.UUID
	Action     string
	Key        string
	ResourceID string
	StatusCode int32
	Body       []byte
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotency,
		arg.ContractID,
		arg.Action,
		arg.Key,
		arg.ResourceID,
		arg.StatusCode,
		arg.Body,
	)
	return err
}
