// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64
	ContractID  pgtype.UUID
	Action      string
	Payload     []byte
	VisitorHash pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type Command struct {
	ID            string
	Vin           string
	Fleet         string
	Action        string
	State         string
	CorrelationID string
	CreatedAt     pgtype.Timestamptz
	SentAt        pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Contract struct {
	ID                pgtype.UUID
	CustomerID        pgtype.UUID
	Vin               string
	InstallmentValue  pgtype.Numeric
	TotalInstallments int32
	PaidCount         int32
	PayerProfile      string
	StartedOn         pgtype.Date
	EndedOn           pgtype.Date
	CreatedAt         pgtype.Timestamptz
}

type Customer struct {
	ID         pgtype.UUID
	Name       string
	HomeLat    pgtype.Float8
	HomeLng    pgtype.Float8
	WorkLat    pgtype.Float8
	WorkLng    pgtype.Float8
	WeekendLat pgtype.Float8
	WeekendLng pgtype.Float8
	CreatedAt  pgtype.Timestamptz
}

type Installment struct {
	ID         pgtype.UUID
	ContractID pgtype.UUID
	DueOn      pgtype.Date
	Amount     pgtype.Numeric
}

type Outbox struct {
	ID        int64
	Topic     string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	SentAt    pgtype.Timestamptz
}

type Payment struct {
	ID            pgtype.UUID
	ContractID    pgtype.UUID
	InstallmentID pgtype.UUID
	Amount        pgtype.Numeric
	Source        string
	PaidAt        pgtype.Timestamptz
}

type Route struct {
	ID        pgtype.UUID
	Version   int32
	Name      string
	Waypoints []byte
	CreatedAt pgtype.Timestamptz
}

type Vehicle struct {
	Vin       string
	Fleet     string
	DisplayID string
	Plate     string
	Model     string
	CreatedAt pgtype.Timestamptz
}

type VehicleState struct {
	Vin       string
	Lat       float64
	Lng       float64
	Battery   int32
	Speed     int32
	Heading   int32
	Ignition  bool
	Locked    bool
	Odometer  float64
	Trip      float64
	UpdatedAt pgtype.Timestamptz
}
