// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retain.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAuditOlderThan = `-- name: DeleteAuditOlderThan :execrows
DELETE FROM audit_log
WHERE created_at < $1
`

func (q *Queries) DeleteAuditOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFinishedCommandsOlderThan = `-- name: DeleteFinishedCommandsOlderThan :execrows
DELETE FROM commands
WHERE updated_at < $1
  AND state IN ('ACKED', 'FAILED', 'TIMEOUT', 'CANCELLED')
`

func (q *Queries) DeleteFinishedCommandsOlderThan(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedCommandsOlderThan, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
