// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicles.sql

package queries

import (
	"context"
)

const getRentalVehicle = `-- name: GetRentalVehicle :one
SELECT vin, fleet, display_id, plate, model
FROM vehicles
WHERE vin = $1 AND fleet = 'rental'
`

type GetRentalVehicleRow struct {
	Vin       string
	Fleet     string
	DisplayID string
	Plate     string
	Model     string
}

func (q *Queries) GetRentalVehicle(ctx context.Context, vin string) (GetRentalVehicleRow, error) {
	row := q.db.QueryRow(ctx, getRentalVehicle, vin)
	var i GetRentalVehicleRow
	err := row.Scan(
		&i.Vin,
		&i.Fleet,
		&i.DisplayID,
		&i.Plate,
		&i.Model,
	)
	return i, err
}

const getVehicleState = `-- name: GetVehicleState :one
SELECT vin, lat, lng, battery, speed, heading, ignition, locked, odometer, trip
FROM vehicle_state
WHERE vin = $1
`

type GetVehicleStateRow struct {
	Vin      string
	Lat      float64
	Lng      float64
	Battery  int32
	Speed    int32
	Heading  int32
	Ignition bool
	Locked   bool
	Odometer float64
	Trip     float64
}

func (q *Queries) GetVehicleState(ctx context.Context, vin string) (GetVehicleStateRow, error) {
	row := q.db.QueryRow(ctx, getVehicleState, vin)
	var i GetVehicleStateRow
	err := row.Scan(
		&i.Vin,
		&i.Lat,
		&i.Lng,
		&i.Battery,
		&i.Speed,
		&i.Heading,
		&i.Ignition,
		&i.Locked,
		&i.Odometer,
		&i.Trip,
	)
	return i, err
}

const insertRentalVehicle = `-- name: InsertRentalVehicle :exec
INSERT INTO vehicles (vin, fleet, display_id, plate, model)
VALUES ($1, 'rental', $2, $3, $4)
ON CONFLICT (vin) DO NOTHING
`

type InsertRentalVehicleParams struct {
	Vin       string
	DisplayID string
	Plate     string
	Model     string
}

func (q *Queries) InsertRentalVehicle(ctx context.Context, arg InsertRentalVehicleParams) error {
	_, err := q.db.Exec(ctx, insertRentalVehicle,
		arg.Vin,
		arg.DisplayID,
		arg.Plate,
		arg.Model,
	)
	return err
}

const listRentalVehicles = `-- name: ListRentalVehicles :many
SELECT vin, fleet, display_id, plate, model
FROM vehicles
WHERE fleet = 'rental'
ORDER BY vin
`

type ListRentalVehiclesRow struct {
	Vin       string
	Fleet     string
	DisplayID string
	Plate     string
	Model     string
}

func (q *Queries) ListRentalVehicles(ctx context.Context) ([]ListRentalVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listRentalVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRentalVehiclesRow{}
	for rows.Next() {
		var i ListRentalVehiclesRow
		if err := rows.Scan(
			&i.Vin,
			&i.Fleet,
			&i.DisplayID,
			&i.Plate,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleState = `-- name: ListVehicleState :many
SELECT vin, lat, lng, battery, speed, heading, ignition, locked, odometer, trip
FROM vehicle_state
ORDER BY vin
`

type ListVehicleStateRow struct {
	Vin      string
	Lat      float64
	Lng      float64
	Battery  int32
	Speed    int32
	Heading  int32
	Ignition bool
	Locked   bool
	Odometer float64
	Trip     float64
}

func (q *Queries) ListVehicleState(ctx context.Context) ([]ListVehicleStateRow, error) {
	rows, err := q.db.Query(ctx, listVehicleState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehicleStateRow{}
	for rows.Next() {
		var i ListVehicleStateRow
		if err := rows.Scan(
			&i.Vin,
			&i.Lat,
			&i.Lng,
			&i.Battery,
			&i.Speed,
			&i.Heading,
			&i.Ignition,
			&i.Locked,
			&i.Odometer,
			&i.Trip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVehicleState = `-- name: UpsertVehicleState :exec
INSERT INTO vehicle_state (
    vin,
    lat,
    lng,
    battery,
    speed,
    heading,
    ignition,
    locked,
    odometer,
    trip,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now()
)
ON CONFLICT (vin) DO UPDATE SET
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    battery = EXCLUDED.battery,
    speed = EXCLUDED.speed,
    heading = EXCLUDED.heading,
    ignition = EXCLUDED.ignition,
    locked = EXCLUDED.locked,
    odometer = EXCLUDED.odometer,
    trip = EXCLUDED.trip,
    updated_at = now()
`

type UpsertVehicleStateParams struct {
	Vin      string
	Lat      float64
	Lng      float64
	Battery  int32
	Speed    int32
	Heading  int32
	Ignition bool
	Locked   bool
	Odometer float64
	Trip     float64
}

func (q *Queries) UpsertVehicleState(ctx context.Context, arg UpsertVehicleStateParams) error {
	_, err := q.db.Exec(ctx, upsertVehicleState,
		arg.Vin,
		arg.Lat,
		arg.Lng,
		arg.Battery,
		arg.Speed,
		arg.Heading,
		arg.Ignition,
		arg.Locked,
		arg.Odometer,
		arg.Trip,
	)
	return err
}
